/* ACTIONS APP CONTEXT GLOBAL */
export const SET_USER_PROFILING = 'SET_USER_PROFILING';
export const SET_INACTIVE = 'SET_INACTIVE';
export const SET_SHOW_ERROR_MODAL = 'SET_SHOW_ERROR_MODAL';
export const SET_USER_AUTH = "SET_USER_AUTH";
